# Generated by Django 3.0.7 on 2023-09-16 09:11

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to=api.models.load_path_video)),
                ('thum', models.ImageField(upload_to=api.models.load_path_thum)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
